global:
  resolve_timeout: 5m

route:
  receiver: default

receivers:
  - name: default
    email_configs:
      - to: "thomas.erven@gmail.com"
        from: "alertmanager@wizartower.dev"
        smarthost: "smtp.example.com:587"
        auth_username: "alertmanager@example.com"
        auth_password: "yourpassword"
        require_tls: true
