apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitower
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    rule_files:
      - "/etc/prometheus/alert.rules.yml"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus:80']

      - job_name: 'grafana'
        static_configs:
          - targets: ['grafana:80']

      - job_name: 'alertmanager'
        static_configs:
          - targets: ['alertmanager:80']

      - job_name: 'glitchtip'
        metrics_path: '/_health/'
        static_configs:
          - targets: ['sentry:9000']

      - job_name: 'harbor-core'
        static_configs:
          - targets: ['harbor-core.harbor.svc.cluster.local:8001']

      - job_name: 'harbor-jobservice'
        static_configs:
          - targets: ['harbor-jobservice.harbor.svc.cluster.local:8001']

      - job_name: 'museit-jacktrip'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['jacktrip2.x-system.co.uk:9100']
      
      - job_name: 'sharemusic-dataverse'
        scrape_interval: 30s
        static_configs:
          - targets: ['cadvisor-sharemusic.wizardtower.dev']

    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager:80']

  alert.rules.yml: |
    groups:
      - name: museit-jacktrip.rules
        rules:
          - alert: HighCPU
            expr: avg(rate(node_cpu_seconds_total{mode!="idle", instance="jacktrip2.x-system.co.uk:9100"}[1m])) > 0.9
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage on {{ $labels.instance }}"
              description: "CPU usage has exceeded 90% for over 5 minutes."

          - alert: HighMemory
            expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) > (26 * 1024 * 1024 * 1024)
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage on {{ $labels.instance }}"
              description: "Memory usage has exceeded 26 GB."

          - alert: DiskUsageHigh
            expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} > 0.7
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High disk usage on {{ $labels.instance }}"
              description: "Disk usage is over 70% on root filesystem."

          - alert: NodeDown
            expr: up{instance="jacktrip2.x-system.co.uk:9100"} == 0
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: "{{ $labels.instance }} is down"
              description: "Node exporter has stopped responding."

      - name: docker.rules
        rules:
          - alert: ContainerHighCPU
            expr: rate(container_cpu_usage_seconds_total{container!=""}[1m]) > 0.5
            for: 2m
            labels:
              severity: warning
              team: sharemusic
            annotations:
              summary: "High CPU usage by container {{ $labels.container }}"
              description: "Container {{ $labels.container }} is using >50% CPU for 2 minutes."

          - alert: ContainerHighMemory
            expr: container_memory_usage_bytes{container!=""} > 500000000
            for: 2m
            labels:
              severity: warning
              team: sharemusic
            annotations:
              summary: "High memory usage by container {{ $labels.container }}"
              description: "Container {{ $labels.container }} is using more than 500MB of RAM."

          - alert: ContainerRestartingFrequently
            expr: rate(container_restart_count{container!=""}[5m]) > 0.1
            for: 5m
            labels:
              severity: warning
              team: sharemusic
            annotations:
              summary: "Container {{ $labels.container }} is restarting frequently"
              description: "Container {{ $labels.container }} has restarted more than once in the last 10 minutes."

          - alert: ContainerDiskUsageHigh
            expr: container_fs_usage_bytes{container!=""} / container_fs_limit_bytes{container!=""} > 0.8
            for: 2m
            labels:
              severity: warning
              team: sharemusic
            annotations:
              summary: "High disk usage by container {{ $labels.container }}"
              description: "Disk usage exceeds 80% for container {{ $labels.container }}."

          - alert: NodeDown
            expr: up{instance="jacktrip2.x-system.co.uk:9100"} == 0
            for: 2m
            labels:
              severity: critical
              team: sharemusic
            annotations:
              summary: "{{ $labels.instance }} is down"
              description: "Node exporter on {{ $labels.instance }} has not responded for 2 minutes."

