apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitower
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus:80']

      - job_name: 'grafana'
        static_configs:
          - targets: ['grafana:80']

      - job_name: 'alertmanager'
        static_configs:
          - targets: ['alertmanager:80']

      - job_name: 'glitchtip'
        metrics_path: '/_health/'
        static_configs:
          - targets: ['sentry:9000']

    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager:9093']
