apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitower
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    rule_files:
      - "/etc/prometheus/alert.rules.yml"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus:80']

      - job_name: 'grafana'
        static_configs:
          - targets: ['grafana:80']

      - job_name: 'alertmanager'
        static_configs:
          - targets: ['alertmanager:80']

      - job_name: 'glitchtip'
        metrics_path: '/_health/'
        static_configs:
          - targets: ['sentry:9000']

    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager:80']

  alert.rules.yml: |
    groups:
      - name: test.rules
        rules:
          - alert: TelegramTestAlert
            expr: vector(1)
            for: 10s
            labels:
              severity: critical
            annotations:
              summary: "🚨 Test alert to Telegram"
              description: "This is a test alert fired by Prometheus to verify Alertmanager integration."
