apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-telegram-bot
  namespace: monitower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-telegram-bot
  template:
    metadata:
      labels:
        app: alertmanager-telegram-bot
    spec:
      containers:
        - name: alertmanager-telegram-bot
          image: metalmatze/alertmanager-bot:0.4.3
          env:
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: alertmanager-telegram-bot-secret
                  key: TELEGRAM_TOKEN
            - name: LISTEN_ADDR
              value: "0.0.0.0:8080"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-telegram-bot
  namespace: monitower
spec:
  selector:
    app: alertmanager-telegram-bot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
