apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitower
data:
  config.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: telegram
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 1h
      routes:
        - matchers:
            - severity="critical"
          receiver: telegram
        - matchers:
            - severity="warning"
          receiver: email

    receivers:
      - name: telegram
        webhook_configs:
          - url: 'https://alertmanager-telegram-bot.mrinjamul.dev/8117780247:AAGzE-z2o5kSlzTSUnDjafRe7hsx6Ur5Inc/-4908129302'
            send_resolved: true

      - name: email
        email_configs:
          - to: "thomas.erven@gmail.com"
            from: "alertmanager@wizartower.dev"
            smarthost: "smtp.example.com:587"
            auth_username: "alertmanager@example.com"
            auth_password: "yourpassword"
            require_tls: true