apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitower
data:
  config.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: telegram
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 1h

    receivers:
    - name: telegram
      telegram_configs:
      - bot_token: '<YOUR_BOT_TOKEN>'
        chat_id: 666230298
        parse_mode: 'Markdown'
        send_resolved: true