apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitower
data:
  config.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: telegram
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 1h

    receivers:
      - name: telegram
        webhook_configs:
          - url: ""http://alertmanager-telegram-bot.monitower.svc.cluster.local:8080/-4908129302"
            send_resolved: true