apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      securityContext:
        fsGroup: 65534
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            envsubst < /etc/alertmanager/config.tpl.yml > /etc/alertmanager/config.yml && \
            /bin/alertmanager --config.file=/etc/alertmanager/config.yml --storage.path=/alertmanager
        env:
          - name: TELEGRAM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: alertmanager-telegram-secret
                key: BOT_TOKEN
          - name: TELEGRAM_CHAT_ID
            valueFrom:
              secretKeyRef:
                name: alertmanager-telegram-secret
                key: CHAT_ID
        ports:
          - containerPort: 9093
        volumeMounts:
          - name: config
            mountPath: /etc/alertmanager
          - name: data
            mountPath: /alertmanager
      volumes:
        - name: config
          configMap:
            name: alertmanager-config
        - name: data
          persistentVolumeClaim:
            claimName: alertmanager-pvc
