apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitower
data:
  config.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: discord
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 1h

    receivers:
      - name: discord
        discord_configs:
          - webhook_url: '${DISCORD_WEBHOOK_URL}'
            title: '{{ .CommonAnnotations.summary }}'
            message: '{{ .CommonAnnotations.description }}'
            send_resolved: true
