apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        args:
          - "--config.file=/etc/alertmanager/config.yml"
        ports:
          - containerPort: 9093
        volumeMounts:
          - name: config
            mountPath: /etc/alertmanager
          - name: alertmanager-data
            mountPath: /alertmanager
      volumes:
        - name: config
          configMap:
            name: alertmanager-config
        - name: alertmanager-data
          persistentVolumeClaim:
            claimName: alertmanager-pvc
